# 🚀 StarLabs 0G - Konfigurasi Optimal
# File ini berisi konfigurasi yang sudah dioptimalkan untuk farming yang efisien

SETTINGS:
  # Threading dan Performance - OPTIMAL UNTUK MULTIPLE WALLET
  # THREADS = Jumlah wallet yang berjalan bersamaan (concurrent)
  #
  # Rekomendasi:
  # - 1-3 wallet: THREADS: 1
  # - 4-10 wallet: THREADS: 3
  # - 11-20 wallet: THREADS: 5
  # - 21+ wallet: THREADS: 3-7 (hati-hati rate limit)
  #
  THREADS: 1 # Optimal: 3-5 thread untuk multiple wallet
  ATTEMPTS: 3 # 3 percobaan sudah cukup
  SHUFFLE_WALLETS: true # Recommended: Acak urutan untuk keamanan
  WAIT_FOR_TRANSACTION_CONFIRMATION_IN_SECONDS: 180 # 3 menit cukup

  # Account Management - KONFIGURASI MULTIPLE WALLET
  ACCOUNTS_RANGE: [0, 0] # 0,0 = gunakan semua akun
  EXACT_ACCOUNTS_TO_USE: [] # Kosong = gunakan range, atau isi [1,2,3,5,7] untuk akun spesifik

  # Timing Optimization (dalam detik) - OPTIMAL UNTUK MULTIPLE WALLET
  PAUSE_BETWEEN_ATTEMPTS: [2, 5] # Lebih cepat untuk retry
  PAUSE_BETWEEN_SWAPS: [30, 60] # Jeda antar swap (dikurangi untuk multiple wallet)
  RANDOM_PAUSE_BETWEEN_ACCOUNTS: [60, 320] # Jeda antar akun (dikurangi)
  RANDOM_PAUSE_BETWEEN_ACTIONS: [15, 90] # Jeda antar aksi (dikurangi)
  RANDOM_INITIALIZATION_PAUSE: [10, 60] # Jeda inisialisasi (spread untuk multiple wallet)

  # Telegram Notifications (Recommended untuk monitoring)
  SEND_TELEGRAM_LOGS: false
  TELEGRAM_BOT_TOKEN: "YOUR_BOT_TOKEN_HERE" # Dapatkan dari @BotFather
  TELEGRAM_USERS_IDS: ["YOUR_USER_ID_HERE"] # ID Telegram Anda

FLOW:
  SKIP_FAILED_TASKS: true # Skip task yang gagal, lanjut ke berikutnya

# Konfigurasi Swap - Optimal untuk profit
ZERO_EXCHANGE_SWAPS:
  BALANCE_PERCENT_TO_SWAP: [1, 10] # Swap 10-25% balance
  NUMBER_OF_SWAPS: [1, 20] # 2-4 swap per sesi

# CAPTCHA Configuration
CAPTCHA:
  SOLVIUM_API_KEY: "" # Recommended: Solvium lebih stabil
  NOCAPTCHA_API_KEY: "YOUR_NOCAPTCHA_KEY"
  USE_NOCAPTCHA: false # false = gunakan Solvium

# RPC Configuration
RPCS:
  ZEROG:
    - https://evmrpc-testnet.0g.ai # RPC utama 0G

# Bridge Configuration - Optimal untuk refuel
CRUSTY_SWAP:
  NETWORKS_TO_REFUEL_FROM:
    - Arbitrum # Network dengan fee rendah
    - Base # Alternative network
  AMOUNT_TO_REFUEL: [0.0005, 0.001] # Amount optimal
  MINIMUM_BALANCE_TO_REFUEL: 0.002 # Minimum balance untuk refuel
  WAIT_FOR_FUNDS_TO_ARRIVE: true
  MAX_WAIT_TIME: 300 # 5 menit max wait
  BRIDGE_ALL: false
  BRIDGE_ALL_MAX_AMOUNT: 0

# Exchange Configuration (Opsional)
EXCHANGES:
  name: OKX # Atau Bitget
  apiKey: "YOUR_API_KEY"
  secretKey: "YOUR_SECRET_KEY"
  passphrase: "YOUR_PASSPHRASE"
  withdrawals:
    - currency: ETH
      networks:
        - Arbitrum # Fee rendah
        - Base # Alternative
      min_amount: 0.001
      max_amount: 0.005
      max_balance: 0.01
      wait_for_funds: true
      max_wait_time: 600 # 10 menit
      retries: 2

# NFT Minting Configuration
MINTS:
  OMNIHUB:
    MAX_PRICE_TO_MINT: 0.001 # Maksimal 0.001 ETH untuk mint

# Referral Configuration
PUZZLEMANIA:
  USE_REFERRAL_CODE: true # Gunakan referral untuk bonus
  INVITES_PER_REFERRAL_CODE: [1, 2]
  COLLECT_REFERRAL_CODE: true

# Technical Settings
OTHERS:
  SKIP_SSL_VERIFICATION: true # Skip SSL untuk proxy
  USE_PROXY_FOR_RPC: false # false = RPC langsung tanpa proxy
  FALLBACK_WITHOUT_PROXY: true # true = fallback ke koneksi langsung jika proxy gagal
  MAX_PROXY_RETRIES: 1 # Maksimal retry dengan proxy sebelum fallback (dikurangi dari 2 ke 1)

# ========================================
# 📝 PANDUAN PENGGUNAAN CEPAT
# ========================================
#
# 1. Ganti semua "YOUR_*" dengan data Anda
# 2. Pastikan file data/ sudah terisi:
#    - private_keys.txt
#    - proxies.txt
#    - twitter_tokens.txt
# 3. Edit tasks.py sesuai kebutuhan
# 4. Jalankan: python main.py
#
# 🎯 TASK RECOMMENDATIONS:
# - Pemula: ["FAUCET", "STORAGESCAN_DEPLOY"]
# - Intermediate: ["FAUCET_TOKENS", "ZERO_EXCHANGE_SWAPS", "CONFT_MINT"]
# - Advanced: Custom task dengan kombinasi semua modul
#
# ⚠️ TIPS KEAMANAN:
# - Gunakan proxy untuk semua operasi
# - Jangan gunakan private key utama
# - Monitor logs secara berkala
# - Backup konfigurasi dan data
# ========================================
